# Generated by Django 3.2.5 on 2021-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidAccounts',
            fields=[
                ('account', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Account')),
            ],
        ),
    ]
