# Generated by Django 3.2.5 on 2021-11-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0001_add_account_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidAccounts',
        ),
    ]
