# Generated by Django 3.2.5 on 2022-01-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presenter', '0002_delete_validaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningCalcHardware',
            fields=[
                ('model_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Model Name')),
                ('hashrate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('power_consumption', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
